header-from: ./.config/header.md

version: ""

formatter: markdown table

name: terraform-aws-transfer-server-ad

content: |-
  {{ .Header }}

  # terraform-aws-transfer-server-ad

  GitHub: [StratusGrid/terraform-aws-transfer-server-ad](https://github.com/StratusGrid/terraform-aws-transfer-server-ad)

  This is a Terraform module to interact with the AWS Transfer Family SFTP service and integrate it Microsoft AD through an AWS Managed AD, or a directory connector.


  <span style="color:red">**Notes:</span>
  - If you're using AWS Managed AD, and you have RADIUS MFA turned on this will *NOT* work. This is an undocumented "feature" of AWS. You will need to create a directory connector to Managed AD in question. Doing this will allow you to bypass the MFA gate.

  ## Example - No Custom DNS

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```

  ## Example - Custom DNS

  ```hcl
  {{ include "examples/example2.tfnot" }}
  ```

  ## Example - Custom S3 Bucket

  ```hcl
  {{ include "examples/example3.tfnot" }}
  ```

  ## Documentation

  ### Notes
  - Due to Terraform limitations this module does not support removing the custom tagging on the `aws_transfer_server.self` resource. See [here](https://github.com/hashicorp/terraform/issues/23679) for more information.

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
